---
name: C2
full_name: C2
type: app
owner_type: project
stage: live
status: active
description: an approval process automation tool
testable: true
team:
- github: afeld
  role: developer
- github: annalee
  role: developer
- github: phirefly
  role: lead
- github: pkarman
  role: developer
- github: yozlet
  role: developer
- github: jessieay
  role: developer

partners:
- GSA National Capital Region
- 18F
- GSA Common Acquisition Platform

stack:
- Ruby
- Rails

services:
- name: CircleCI
  category: testing
  url: https://circleci.com/gh/18F/C2
  badge: https://circleci.com/gh/18F/C2.svg?style=svg
- name: Code Climate
  category: testing
  url: https://codeclimate.com/github/18F/C2
  badge: https://codeclimate.com/github/18F/C2/badges/gpa.svg
- name: Gemnasium
  category: dependency status
  url: https://gemnasium.com/18F/C2
  badge: https://gemnasium.com/18F/C2.svg

licenses:
  C2:
    name: "CC0-1.0"
    url: https://github.com/18F/C2/blob/master/LICENSE.md

links:
- url: https://cap.18f.gov/
  text: C2 website

contact:
- url: https://cap.18f.gov/feedback
  text: C2 support
- url: https://github.com/18F/C2/issues
  text: C2 GitHub issues
