---
engines:
  coffeelint:
    enabled: true
  csslint:
    enabled: true
  eslint:
    enabled: true
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/AndOr:
        enabled: false
  bundler-audit:
    enabled: true
  brakeman:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
exclude_paths:
- "**/*.scss"
- db/migrate/*
- db/schema.rb
- spec/**/*
- vendor/**/*
