---
engines:
  coffeelint:
    enabled: true
  csslint:
    enabled: true
  eslint:
    enabled: true
  rubocop:
    enabled: true
    exclude_fingerprints:
    - 348b45047efd6d1aa39a460705e5a494
    checks:
      Rubocop/Style/AndOr:
        enabled: false
      Rubocop/Style/ExtraSpacing:
        enabled: false
      Rubocop/Style/GuardClause:
        enabled: false
      Rubocop/Style/IfUnlessModifier:
        enabled: false
      Rubocop/Style/RaiseArgs:
        enabled: false
      Rubocop/Style/PredicateName:
        enabled: false
  bundler-audit:
    enabled: true
  brakeman:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript

    exclude_fingerprints:
    - 723745172624c70737431734e7227dad
    - 5a6ed15b3c21a7acd8338d8fa7a98a63
    - de64cf3a4cb202d07f05cc83b0c67708
    - ac193f2c601eab797ead45097b632186
    - b3f0319ee7c7f104c6d579b01fe8ebc5 # https://github.com/18F/C2/pull/1624

ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
exclude_paths:
- "**/*.scss"
- db/migrate/*
- db/schema.rb
- spec/**/*
- vendor/**/*
