AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Enabled: false

Rails:
  Enabled: true

Style/CommentAnnotation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DotPosition:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: true

Style/IfUnlessModifier:
  Description: >-
                 Favor modifier if/unless usage when you have a
                 single-line body.
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#if-as-a-modifier'
  Enabled: true

Style/RedundantBegin:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/AndOr:
  EnforcedStyle: always

ClassLength:
  Max: 250
