AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
Rails:
  Enabled: true
Metrics/LineLength:
  Enabled: false
Style/CommentAnnotation:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DotPosition:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  # inline conditionals don't get picked up by simplecov, so preferable to avoid them
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/AndOr:
  Enabled: false
ClassLength:
  Max: 250
