after_failure:
  - mysql -e 'show databases;'
  - cat ./config/database.yml
  - echo $RAILS_ENV
  - bundle exec rake --version
  - ruby env
before_script:
  - mysql -e 'create database c2_test;'
  - cp config/database.yml.example config/database.yml
  - npm install -g grunt-cli
install:
  - bundle install --without development
  - npm install
language: ruby
notifications:
  email:
    recipients:
      - raphael.villas@gsa.gov
      - robert.read@gsa.gov
      - alexander.magee@gsa.gov
      - anna.flowerhorne@gsa.gov
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
  - grunt jasmine
services:
  - mysql
rvm:
  - 2.0.0
branches:
  only:
    - master
    - /^ci[-_].*$/

env: NOTIFICATION_FROM_EMAIL=test-reply-communicart.sender@some-dot-gov.gov