after_failure:
  - mysql -e 'show databases;'
  - cat ./config/database.yml
  - echo $RAILS_ENV
  - bundle exec rake --version
  - ruby env
before_script:
  - script/bootstrap
language: ruby
notifications:
  email:
    recipients:
      - aidan.feldman@gsa.gov
      - alexander.magee@gsa.gov
      - raphael.villas@gsa.gov
script:
  - bundle exec rake spec
  - grunt jasmine
services:
  - mysql
rvm:
  - 2.0.0
branches:
  only:
    - master
    - /^ci[-_].*$/

env: NOTIFICATION_FROM_EMAIL=test-reply-communicart.sender@some-dot-gov.gov
