after_failure:
  - mysql -e 'show databases;'
  - cat ./config/database.yml
  - echo $RAILS_ENV
  - bundle exec rake --version
  - ruby env
before_script:
  - script/bootstrap
cache:
  - bundler
  - npm
language: ruby
notifications:
  email:
    recipients:
      - aidan.feldman@gsa.gov
      - alexander.magee@gsa.gov
      - raphael.villas@gsa.gov
script:
  - bundle exec rspec spec
  - grunt jasmine
services:
  - mysql
rvm:
  - 2.0.0
env:
  global:
    # https://github.com/codeclimate/ruby-test-reporter/issues/28#issuecomment-60523477
    - secure: CODECLIMATE_REPO_TOKEN=e10db1a0de46345d5588bd6364efbd873b220b1f904eb4604eaa47343fa75d22
    - NOTIFICATION_FROM_EMAIL=test-reply-communicart.sender@some-dot-gov.gov
