box:
  image: busybox
  volumes:
    - /box

elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
db:
  image: postgres:9
  ports:
    - "5432"
  environment:
    - DATABASE_NAME=c2_development
web:
  build: .
  env_file: .env
  environment:
    DATABASE_USER: postgres
    DATABASE_NAME: c2_development
    DATABASE_HOST: db
  volumes:
    - .:/app
  ports:
    - "5000:5000"
  links:
    - db
    - elasticsearch
  volumes_from:
    - box