version: '2'
services:
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
  web:
    build: .
    command: bin/docker-start
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_PASSWORD=
      - POSTGRESQL_USERNAME=postgres
      - REDIS_HOST=redis
      - DEVISE_ADMIN_EMAIL=admin@example.com
    links:
      - postgres
      - elasticsearch
      - redis
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - elasticsearch
      - redis
volumes:
  elasticsearch: {}
  postgres: {}
  redis: {}