default: &DEFAULT
  engine: Proposal
  joins:
    requester: true
    gsa18f_procurements:
      engine: Gsa18f::Procurement
      on_clause: gsa18f_procurements.id = proposals.client_data_id AND proposals.client_data_type = 'Gsa18f::Procurement'
      outer: true
    ncr_work_orders:
      engine: Ncr::WorkOrder
      on_clause: ncr_work_orders.id = proposals.client_data_id AND proposals.client_data_type = 'Ncr::WorkOrder'
      outer: true
  sort: -created_at
  columns:
    - &public_id
      db_field: public_id
      header: ID
      formatter: link
    - &name
      display_field: name
      header: Request
      formatter: link
    - &requester
      db_field: requester.email_address
      header: Requester
    - &status
      db_field: status
      header: Status
      formatter: review_status
      sort_expr: >
        CASE proposals.status
        WHEN 'pending' THEN 1
        WHEN 'approved' THEN 2
        ELSE 3
        END
    - &created_at
      db_field: created_at
      header: Submitted
      formatter: date

ncr:
  <<: *DEFAULT
  columns:
    - <<: *public_id
    - <<: *name
    - <<: *requester
    - db_field: ncr_work_orders.amount
      display_field: client_data.total_price
      header: Total Price
      formatter: currency
    - <<: *status
    - <<: *created_at

gsa18f:
  <<: *DEFAULT
  columns:
    - <<: *public_id
    - <<: *name
    - <<: *requester
    - display_field: client_data.total_price
      header: Total Price
      formatter: currency
      sort_expr: gsa18f_procurements.cost_per_unit * gsa_procurements.quantity
    - <<: *status
    - <<: *created_at
