default: &DEFAULT
  engine: Proposal
  joins:
    requester: true
    gsa18f_procurements: >
      LEFT JOIN gsa18f_procurements
      ON (gsa18f_procurements.id = proposals.client_data_id
      AND proposals.client_data_type = 'GSA18f::Procurement')
    ncr_work_orders: >
      LEFT JOIN ncr_work_orders
      ON (ncr_work_orders.id = proposals.client_data_id
      AND proposals.client_data_type = 'Ncr::WorkOrder')
  sort: -created_at
  column_configs: &COLUMN_CONFIGS
    public_id:
      header: ID
      formatter: link
    name:
      virtual: true
      header: Request
      formatter: link
    requester:
      db: requester.email_address
      display: requester.email_address
    status:
      db: >
        CASE proposals.status
        WHEN 'pending' THEN 1
        WHEN 'approved' THEN 2
        ELSE 3
        END
      formatter: review_status
    created_at:
      formatter: date
      header: Submitted
  columns:
    - public_id
    - name
    - requester
    - status
    - created_at

ncr:
  <<: *DEFAULT
  column_configs:
    <<: *COLUMN_CONFIGS
    total_price:
      db: ncr_work_orders.amount
      display: client_data.total_price
      formatter: currency
  columns:
    - public_id
    - name
    - requester
    - total_price
    - status
    - created_at

gsa18f:
  <<: *DEFAULT
  column_configs:
    <<: *COLUMN_CONFIGS
    total_price:
      db: gsa18f_procurements.cost_per_unit * gsa_procurements.quantity
      display: client_data.total_price
      formatter: currency
  columns:
    - public_id
    - name
    - requester
    - total_price
    - status
    - created_at
