default: &DEFAULT
  engine: Proposal
  joins:
    requester: true
    gsa18f_procurements: >
      LEFT JOIN gsa18f_procurements
      ON (gsa18f_procurements.id = proposals.client_data_id
      AND proposals.client_data_type = 'Gsa18f::Procurement')
    ncr_work_orders: >
      LEFT JOIN ncr_work_orders
      ON (ncr_work_orders.id = proposals.client_data_id
      AND proposals.client_data_type = 'Ncr::WorkOrder')
  sort: -created_at
  column_configs:
    public_id:
      header: ID
      formatter: link
    name:
      virtual: true
      header: Request
      formatter: link
    requester:
      db: requester.email_address
      display: requester.email_address
    status:
      db: >
        CASE proposals.status
        WHEN 'pending' THEN 1
        WHEN 'approved' THEN 2
        ELSE 3
        END
      formatter: review_status
    created_at:
      formatter: date
      header: Submitted
    updated_at:
      formatter: date
      header: Last Updated
    total_price:
      db: COALESCE(ncr_work_orders.amount, gsa18f_procurements.cost_per_unit * gsa18f_procurements.quantity, 0)
      display: client_data.total_price
      formatter: currency
      header: Amount
    urgency:
      header: Urgency
      db: gsa18f_procurements.urgency
      display: client_data.urgency_string
    purchase_type:
      header: Purchase
      db: gsa18f_procurements.purchase_type
      display: client_data.purchase_type
    vendor:
      header: Vendor
      display: client_data.vendor
    expense_type:
      header: Expense
      display: client_data.expense_type
    building_number:
      header: Building
      display: client_data.building_number
    rwa_number:
      header: RWA
      display: client_data.rwa_number
    work_order_code:
      header: WO
      display: client_data.work_order_code
    direct_pay:
      header: Direct
      display: client_data.direct_pay
    cl_number:
      header: CL
      display: client_data.cl_number
    function_code:
      header: Function
      display: client_data.function_code
    pegasys_document_number:
      header: Pegasys
      display: client_data.pegasys_document_number
    is_tock_billable:
      header: Billable
      display: client_data.is_tock_billable
    tock_project:
      header: Tock
      display: client_data.tock_project
    client_billed:
      header: Billed
      display: client_data.client_billed
    soc_code:
      header: SOC
      display: client_data.soc_code
    duty_station:
      header: Duty station
      display: client_data.duty_station
    supervisor_id:
      header: Supervisor
      display: client_data.supervisor_id
    title_of_event:
      header: Event title
      display: client_data.title_of_event
    event_provider:
      header: Event provider
      display: client_data.event_provider
    purpose:
      header: Event purpose
      display: client_data.purpose
    justification:
      header: Justification
      display: client_data.justification
    link:
      header: Event link
      display: client_data.link
    instructions:
      header: Instructions
      display: client_data.instructions
    nfs_form:
      header: Nfs form
      display: client_data.nfs_form
    estimated_travel_expenses:
      header: Estimated travel expenses
      display: client_data.estimated_travel_expenses
    start_date:
      header: Event start date
      display: client_data.start_date
    end_date:
      header: Event end date
      display: client_data.end_date
    type_of_event:
      header: Event type
      display: client_data.type_of_event
    free_event:
      header: Free event
      display: client_data.free_event
    travel_required:
      header: Travel required
      display: client_data.travel_required
  columns:
    - public_id
    - name
    - requester
    - status
    - created_at

ncr:
  <<: *DEFAULT
  columns:
    - public_id
    - name
    - requester
    - total_price
    - status
    - created_at
    - vendor
    - expense_type
    - building_number
    - rwa_number
    - work_order_code
    - direct_pay
    - cl_number
    - function_code
    - soc_code

gsa18f:
  <<: *DEFAULT
  columns:
    - public_id
    - name
    - requester
    - total_price
    - status
    - created_at
    - urgency
    - is_tock_billable
    - tock_project
    - purchase_type
    - pegasys_document_number
    - client_billed
    - duty_station
    - title_of_event
    - event_provider
    - purpose
    - link
    - nfs_form
    - estimated_travel_expenses
    - start_date
    - end_date
    - type_of_event
    - free_event
    - travel_required
