development:
  secret_key_base: <%= "x" * 30 %>

test:
  secret_key_base: <%= "x" * 30 %>

staging:
  secret_key_base: <%= ENV.fetch('SECRET_TOKEN') if Rails.env.staging? %>

production:
  secret_key_base: <%= AppParamCredentials.secret_token if Rails.env.production? %>
