#!/bin/sh

set -e
set -x

# create config files, if not already present
if [ ! -f .env ]; then
  cp .env.example .env
fi

bundle

npm install -g grunt-cli
npm install

bundle exec rake db:setup
RAILS_ENV=test bundle exec rake db:setup

echo "DONE"
