#!/bin/sh

set -e
set -x

# http://stackoverflow.com/a/677212/358804
if ! hash cf-blue-green 2>/dev/null; then
  # http://stackoverflow.com/a/23550347/358804
  >&2 echo "Please install cf-blue-green.\n\n\thttps://github.com/18F/cf-blue-green\n"
  exit 1
fi

TAG=$(date -u +"%Y-%m-%dT%H%M%S")

git tag $TAG
cf-blue-green c2-prod
git push origin $TAG
