#!/bin/sh

set -e
set -x


# record the deployment in New Relic
# https://docs.newrelic.com/docs/agents/ruby-agent/features/recording-deployments-ruby-agent#Manual
# TODO track who deployed, and what revision
if [ -n "$NEW_RELIC_LICENSE_KEY" ]; then
  bundle exec newrelic deployments
fi

./script/start
