#!/bin/sh

bundle check || bundle install

set -e
set -x

# default the port, for development
# http://stackoverflow.com/a/6859838/358804
PORT=${PORT-3000}

bundle exec rake cf:on_first_instance db:migrate db:seed
bundle exec puma -p ${PORT} -C ./config/puma.rb
